### ISSUE TITLE
Add & remove guest base on number of guest per unit

### ISSUE THREAD

**Issue by theachoem** [channainfo/commissioner#1062]
## Task breakdown:
- [x] Refactor to get number of guest of line item & variant
- [x] Add service to add guest
- [x] Add service to remove guest
- [x] Turn above services into API

## What next?
- [ ] Add age restriction
- [ ] Add guest validation

### Related PR on App + Demo:
- https://github.com/bookmebus/cm-market-app/pull/1105
