### ISSUE TITLE
Checklist for the 1st public release

### ISSUE THREAD

**Issue by channainfo** [channainfo/commissioner#192]
# Check list

 - [ ] Checkout flow
 - [ ] Payment Gateways integrations
 - [ ] Admin managements
 - [ ] Infrastructure setup
 - [ ] Analytics
 - [ ] H5 options for web
 - [ ] UI reviews
 - [ ] Beta test

**Comment by theachoem** [comment]
Related issue: #163 

# CM Deploy before KNY
## Must have
- [ ] Checkout glitch
- [ ] ABA integration
- [ ] Price by date [Service Calender]
- [ ] Review
- [ ] Notification
- [ ] Deploy the app first

## Key note features
- Dynamic Section
- Calculate number of guest
- Search by Map
- Tax between days
- Service calendar
- Change date
- Can be server down

**Comment by theachoem** [comment]
## Hotel Card
- Location: nearby place
- Row: Show all promoted option values
- List: 
  - Room left
  - Price Rules
- Pricing from only

**Comment by theachoem** [comment]
Close as released
