### ISSUE TITLE
BookMe+ 2024 Issues & Improvements

### ISSUE THREAD

**Issue by theachoem** [channainfo/commissioner#2165]
# Tasks

## I. Commissioner
- [ ] 1. Enqueue generate BIB
- [ ] 2. Bug: recalculate conversion not working
    -   Api click to fetch
- [ ] 3. Waiting room: Store which page is waiting to enter (page path) 
    -   Allow api to pass path from app & server save it.
- [ ] 4. Writing rails logs in waiting room
- [ ] 5. Improve event setup admin (make it easier to setup and faster load)
- [ ] 6. Custom KYC fields + translated too

## II. Cm-market-app
- [ ] 1. Fix add to cart show free entry during enqueue (should show loading)
- [ ] 2. Show payment state in ticket card
- [ ] 3. Download app button not work on web app
    - Fix by avoid click on banner if can’t purchase on web 👈
- [ ] 4. Show smaller quantity sheet when product has only 1 variant  @leak
- [ ] 5. Guests view improvement - to changes:
    - a. Swap to show delete button
    - b. Show “done” instead of “cancel” button
- [ ] 6. Show snack bar alert “Limited X items per transactions” when editing quantity in cart.
- [ ] 7. Paginate bookings by 10 (make sure to use compute)
- [ ] 8. Canceled bookings page
- [ ] 9. Payment processing
    - Stop check payment status after 1mn expired
- [ ] 10. Huawei app gallery with fastlane
- [ ] 11. Cache event / product details
- [ ] 12. Paginate notification

## III. Cm-market-client
- [ ] 1. Improve: show product / ticket UI during flutter loading [similar to event](https://www.bookme.plus/t/events/siem-reap-shuttle-tours).

## IV. Commissioner + Cm-client
- [ ] 1. View anonymous ticket with JWT

## V. Vpago
- [ ] 1. Saved card

**Comment by theachoem** [comment]
![Image](https://github.com/user-attachments/assets/8d92c444-eb5b-4b37-b92b-0976cb21261c)
