### ISSUE TITLE
Weekly DEV Team Meeting | 06 Dec 2023

### ISSUE THREAD

**Issue by theachoem** [channainfo/commissioner#870]
## Todo
- [ ] Blogs
- [ ] TED talk event integration. 
   - https://github.com/bookmebus-backend/cm-market-app/issues/930
- [x] #871
  - Integrate server (spree_vpago)
  - Integrate app
    - cm-market-client
    - cm-market-app
- [x] Home Dynamic Sections
  - [x] https://github.com/bookmebus-backend/cm-market-app/issues/917
- [x] Customer Notification
   - Cm-market-app
     - https://github.com/bookmebus-backend/cm-market-app/issues/938
     - https://github.com/bookmebus-backend/cm-market-app/issues/946
   - Commissioner
     - https://github.com/channainfo/commissioner/issues/875
     - https://github.com/channainfo/commissioner/issues/874
     - https://github.com/channainfo/commissioner/issues/888
- [ ] Landing page web
- [ ] Hotel price only holiday
- [ ] Stock not decreasing
   - https://github.com/channainfo/commissioner/issues/847
- [ ] Affiliate
- [ ] Full-featured Event
- [ ] Confirmed user when user confirms email/phone:
   - https://github.com/channainfo/commissioner/issues/865
- [ ] Ensure new master bookings UI flow ready to publish
- [x] Product Map (in ticket UI, map should base on variant stock location)
    -  https://github.com/bookmebus-backend/cm-market-app/issues/922
## Projects
- https://github.com/bookmebus/cm-market-server
- https://github.com/channainfo/commissioner
- https://github.com/bookmebus-backend/cm-market-client
- https://github.com/bookmebus-backend/cm-market-app
- https://github.com/bookmebus/spree_vpago

**Comment by theachoem** [comment]
- More focus
- What to deliver this week?
- Pick your task, and commit to finish this week

Expect outcome
- 2, 3 tasks

**Comment by theachoem** [comment]
@srey-moch
