### ISSUE TITLE
Specific Deal Hotels - /t/promotions/20-percent-off-on-KN

### ISSUE THREAD

**Issue by theachoem** [channainfo/commissioner#929]
# Tasks Breakdown

- [x] Create a taxon_vendor and then connect the vendor and taxon.
- [x] In vendor page, allow to add taxons (same to products edit page)
- [x] Add vendors to the taxon API (add vendors to serializer)
- [x] Create a deal page in the app (in cm-market-app)

**Comment by theachoem** [comment]
Close as completed
